-- V1_1_0__InitDataCharge.sql
INSERT INTO PRODUCTS (PRODUCT_ID, PRODUCT_NAME)
VALUES (35455, 'Camiseta Básica');
INSERT INTO PRODUCTS (PRODUCT_ID, PRODUCT_NAME)
VALUES (1, 'Pantalón Chino');
INSERT INTO PRODUCTS (PRODUCT_ID, PRODUCT_NAME)
VALUES (2, 'Chaqueta Denim');